# Generated by Django 2.2.20 on 2021-09-27 11:59

from django.db import migrations


def copy_flats_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner = Owner.objects.get(owner=flat.owner,
            owner_pure_phone = flat.owner_pure_phone)
        owner.flat.set([flat])

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20210927_1451'),
    ]

    operations = [
        migrations.RunPython(copy_flats_to_owner),
    ]
