# Generated by Django 2.2.20 on 2021-09-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_auto_20210927_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='Flat',
            name='owners_phonenumber',
        ),
        migrations.RemoveField(
            model_name='Flat',
            name='owner_pure_phone',
        ),
    ]
