# Generated by Django 2.2.20 on 2021-10-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20210927_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(db_index=True, null=True, related_name='flats', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
